# Global Settings
region: 'us-east-1'
scaling:
    max_concurrency: 50
    min_containers: 1
    max_containers: 50

# Add your functions here
lambda_functions:
    - name: 'your-function-here'
      # The parameters below are optional. X-Lambda will default to the global
      # settings, if not set on the function level
      region: 'us-east-1'
      scaling:
        max_concurrency: 5
        min_containers: 1
        max_containers: 5
    - name: 'yet-another-function'
